### ISSUE TITLE
0.6 map scrolling turns off

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#322] opened 2023-02-10 03:38 UTC
map scrolling turns off after reading the message
also appears after building actions

https://user-images.githubusercontent.com/2237225/217994393-bb5ccb33-2f58-4435-9929-424e22b18058.mp4

The problem disappears when I use zoom

**Comment by zdechlak** [comment] 2023-02-10 03:44
it seems that this error occurs when the zoom is in a position other than the maximum zoom out

![image](https://user-images.githubusercontent.com/2237225/217995252-c86ef011-31e5-4fec-9455-484635a1bb08.png)
then the error does not appear

![image](https://user-images.githubusercontent.com/2237225/217995422-1b801982-41b5-4493-a56b-d246fea64519.png)
the error appears all the time on this zoom setting

**Comment by zdechlak** [comment] 2023-02-10 03:59
https://user-images.githubusercontent.com/2237225/217997258-6053add3-e77c-497a-b060-9baa392eb0f9.mp4

**Comment by tlongstretch** [comment] 2023-02-11 00:21
I think I have found the cause of this.  The logic that determines what is in scope (which object being clicked on) is not scaling with zoom, so the more zoomed you are the more likely it will occur.  This happens when clicking in the right or lower part of the screen, but should resolve itself if you click on the upper/left parts of the screen.   

I am reworking the entire zoom code now to separate UI zoom from game viewport zoom,  so this should be solved as part of that rework

**Comment by tlongstretch** [comment] 2023-02-11 04:40
new zoom is working now, it should make debugging popup/drag issues simpler also

**Comment by tlongstretch** [comment] 2023-02-11 21:56
this issue should now be fixed in v0.6.1

**Closed as completed by tlongstretch** 2023-02-11 21:56 UTC
