### ISSUE TITLE
option_CanTransportSerfsInBoats is buggy, can result in stuck serfs & sailors

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#283] opened 2023-01-19 20:10 UTC
[a1.zip](https://github.com/forkserf/forkserf/files/10460677/a1.zip) << save

https://user-images.githubusercontent.com/2237225/213549355-134cd196-ab4d-47c8-bbaa-907e9b204df0.mp4

**Comment by tlongstretch** [comment] 2023-01-19 20:17
Do you have option_CanTransportSerfsInBoats enabled?  If so, I have seen this behavior sometimes, it needs additional work to resolve.  

If you are seeing this WITHOUT option_CanTransportSerfsInBoats, that is something I haven't seen before and will have to investigate

**Comment by zdechlak** [comment] 2023-01-19 21:13
CanTransportSerfsInBoats enabled

**Comment by tlongstretch** [comment] 2023-01-19 21:26
Ah, yes, I need to make a note that this feature is unstable.  Please let me know if you see any issues like this with it DISabled

**Comment by tlongstretch** [comment] 2023-02-17 00:46
I was hopeful that having only a single land road to a water route would prevent it from bugging, but I am still seeing issues.  Will have to do more testing

**Comment by tlongstretch** [comment] 2023-02-18 17:09
looks like one condition where it commonly shows a bug is when a sailor is approaching a flag to pick up a resource to transport on the water route, but a serf is also approaching the flag to be transported.  I think it is noticing  the serf and trying to pick him up even though he isn't in WaitForBoat state yet, instead of picking up the resource

**Comment by tlongstretch** [comment] 2023-02-22 01:10
might have found the cause of this (and potential fix) - I have a check to prevent a sailor from switching with a serf approaching the flag pos to prevent a condition where they would switch and a land serf would walk on water.  However, the check needs to return the functio early and instead it is letting it continue which assigns two serfs the same pos and the same serf with the same index is shown in two places on the map.  

testing to see if I can reproduce after fix added...

**Comment by tlongstretch** [comment] 2023-02-22 02:19
turned out an additional issue.. needed to fix an earlier part to allow the arriving serf to enter WaitForBoat state, I think this may be fixed now can't reproduce it anymore after a couple tries

**Closed as completed by tlongstretch** 2023-02-22 02:19 UTC
Labels: bug
