### ISSUE TITLE
the forester suspends the game

### ISSUE THREAD

**Issue by zdechlak** [forkserf/forkserf#316] opened 2023-02-05 23:34 UTC
![image](https://user-images.githubusercontent.com/2237225/216852301-2b3291a6-f410-4451-81f5-a09ad8dbb04b.png)

recently started playing with all the changes implemented, the game often crashes even before the castle is built.

It often crashes when I play on an unusual map, e.g. a lot of water.

I'm still investigating which new elements cause the game to crash (but now I'm very busy and can't play as much as before)

So far, I've rather played on standard settings and the game runs quite stable

**Comment by zdechlak** [comment] 2023-02-06 01:20
the game is crashed by the settler when the tree is planted

![image](https://user-images.githubusercontent.com/2237225/216860405-2a9d26bf-eaf0-4ae1-8e25-1da6464b5cf8.png)

**Comment by tlongstretch** [comment] 2023-02-06 22:37
the crashing on maps with lots of water is might be due to the AIs being unable to find an acceptable place to build castle, if this happens it will log an exception, check console.out.   I want to make this a popup warning or go back to game setup screen instead of crashing.

**Comment by tlongstretch** [comment] 2023-02-06 23:27
for the forester issue, I am almost positive I found the cause, it is related to option_ForestersCreateMonoculture, to avoid it disable the option for now, I have fixed in unstable branch and will include in next release

**Closed as completed by tlongstretch** 2023-02-06 23:27 UTC
